# Generated by Django 5.2.1 on 2025-06-02 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tunisia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('youth_unemployment', models.FloatField(blank=True, null=True)),
                ('female_unemployment', models.FloatField(blank=True, null=True)),
                ('labor_force_participation', models.FloatField(blank=True, null=True)),
                ('average_wage', models.FloatField(blank=True, null=True)),
                ('job_creation_rate', models.FloatField(blank=True, null=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_market_data', to='tunisia.tunisiagovernorate')),
            ],
            options={
                'verbose_name_plural': 'Labor Market Data',
                'unique_together': {('governorate', 'year')},
            },
        ),
    ]
