# Generated by Django 5.2.1 on 2025-06-01 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('continent', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('headline_consumer_price_inflation', models.FloatField(blank=True, null=True)),
                ('energy_consumer_price_inflation', models.FloatField(blank=True, null=True)),
                ('food_consumer_price_inflation', models.FloatField(blank=True, null=True)),
                ('official_core_consumer_price_inflation', models.FloatField(blank=True, null=True)),
                ('producer_price_inflation', models.FloatField(blank=True, null=True)),
                ('gdp_deflator_index_growth_rate', models.FloatField(blank=True, null=True)),
                ('happiness_score', models.FloatField(blank=True, null=True)),
                ('gdp_per_capita', models.FloatField(blank=True, null=True)),
                ('social_support', models.FloatField(blank=True, null=True)),
                ('healthy_life_expectancy_at_birth', models.FloatField(blank=True, null=True)),
                ('freedom_to_make_life_choices', models.FloatField(blank=True, null=True)),
                ('generosity', models.FloatField(blank=True, null=True)),
                ('perceptions_of_corruption', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_indicators', to='countries.country')),
            ],
            options={
                'ordering': ['-year', 'country__name'],
                'unique_together': {('country', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'country')},
            },
        ),
    ]
