# Generated by Django 5.2.1 on 2025-06-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TunisiaGovernorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('arabic_name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population_2024', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('agricultural_land_percent', models.FloatField(blank=True, null=True)),
                ('population_density', models.FloatField(blank=True, null=True)),
                ('labor_force_size', models.IntegerField(blank=True, null=True)),
                ('gdp_contribution', models.FloatField(blank=True, null=True)),
                ('coastal_access', models.BooleanField(default=False)),
                ('industrial_zones', models.IntegerField(blank=True, null=True)),
                ('tourist_attractions', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxIncentives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('incentive_type', models.CharField(max_length=100)),
                ('tax_reduction_percent', models.FloatField(blank=True, null=True)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_incentives', to='tunisia.tunisiagovernorate')),
            ],
            options={
                'unique_together': {('governorate', 'sector', 'incentive_type')},
            },
        ),
        migrations.CreateModel(
            name='RealEstatePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('residential_price_per_m2', models.FloatField(blank=True, null=True)),
                ('commercial_price_per_m2', models.FloatField(blank=True, null=True)),
                ('land_price_per_m2', models.FloatField(blank=True, null=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_prices', to='tunisia.tunisiagovernorate')),
            ],
            options={
                'unique_together': {('governorate', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('tourism', 'Tourism'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('services', 'Services')], max_length=20)),
                ('overall_score', models.FloatField()),
                ('labor_score', models.FloatField(blank=True, null=True)),
                ('infrastructure_score', models.FloatField(blank=True, null=True)),
                ('tax_incentive_score', models.FloatField(blank=True, null=True)),
                ('market_access_score', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_scores', to='tunisia.tunisiagovernorate')),
            ],
            options={
                'unique_together': {('governorate', 'sector')},
            },
        ),
    ]
