# Generated by Django 5.2.1 on 2025-06-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('arabic_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population_2024', models.IntegerField()),
                ('area_km2', models.FloatField()),
                ('unemployment_rate', models.FloatField()),
                ('agricultural_land_percent', models.FloatField()),
                ('population_density', models.FloatField()),
                ('labor_force_size', models.IntegerField()),
                ('gdp_contribution', models.FloatField()),
                ('coastal_access', models.BooleanField()),
                ('industrial_zones', models.IntegerField()),
                ('tourist_attractions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaborMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('unemployment_rate', models.FloatField()),
                ('youth_unemployment', models.FloatField()),
                ('female_unemployment', models.FloatField()),
                ('labor_force_participation', models.FloatField()),
                ('average_wage', models.FloatField()),
                ('job_creation_rate', models.FloatField()),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_data', to='governorates.governorate')),
            ],
            options={
                'unique_together': {('governorate', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('residential_price_per_m2', models.FloatField()),
                ('commercial_price_per_m2', models.FloatField()),
                ('land_price_per_m2', models.FloatField()),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_data', to='governorates.governorate')),
            ],
            options={
                'unique_together': {('governorate', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_investment_offices', models.TextField(blank=True, null=True)),
                ('relevant_government_agencies', models.TextField(blank=True, null=True)),
                ('required_permits_procedures', models.TextField(blank=True, null=True)),
                ('timeline_for_setup', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_size_recommendations', models.TextField(blank=True, null=True)),
                ('ranking_score', models.IntegerField(blank=True, null=True)),
                ('infrastructure_details', models.TextField(blank=True, null=True)),
                ('economic_incentives', models.TextField(blank=True, null=True)),
                ('geographic_advantages', models.TextField(blank=True, null=True)),
                ('cost_analysis_summary', models.TextField(blank=True, null=True)),
                ('success_stories', models.TextField(blank=True, null=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='governorates.governorate')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='governorates.sector')),
            ],
            options={
                'unique_together': {('governorate', 'sector')},
            },
        ),
    ]
